In [37]:
#Calculo de pasos del ejemplo, en caliente
import numpy as np

a = [(2,8),(5,3),(7,6),(1,4),(9,2),(4,7),(6,1)]
n = len(a)
c1 = [] ; c2 = []
for i in range(n):
    c1.append(a[i][0])
    c2.append(a[i][1])
A = np.array([c1,c2])
A = A.T
print(A)
c = A.sum(axis=0)/len(A)
print(c)
def distancia(a,b):
    d = 0
    n = len(a)
    for i in range(n):
        d +=(a[i] - b[i])**2
    return d**0.5
def mayor_distancia(c,puntos):
    d_max = -float('inf')
    for e in puntos:
        d = distancia(c,e)
        if d > d_max:
            d_max = d
    return d_max
radio = mayor_distancia(c,A)
print(radio)
def varianza(A):
    c = A.sum(axis=0)/len(A)
    var = []
    for i in range(len(A[0])):
        var.append(sum((A[:,i]-c[i])**2)/len(A))
    return var
print(varianza(A))
def ind_maximo(array):
    ind_mayor = -1
    mayor = -float('inf')
    for i in range(len(array)):
        if array[i]>mayor:
            ind_mayor = i
            mayor = array[i]
    ejes = ["X","Y","Z"]
    return ejes[ind_mayor],ind_mayor
eje_mayor_varianza,ind_eje = ind_maximo(varianza(A)) #asigna por posicion ,no por nombre de variables
print(eje_mayor_varianza)
def ordenar(A_,eje):
    n = len(A_)
    for i in range(1,n):
        p = A_[i].copy()
        valor = A_[i,eje]
        j = i - 1 
        while j>=0 and A_[j,eje]>valor:
            A_[j + 1] = A_[j]
            j = j - 1 
        A_[j + 1] = p
    return A_
def dividir_eje_mediana(A,eje): 
    A_eje = A.copy()
    #print(A_eje)
    A_ordenado = ordenar(A_eje,eje)
    #print(A_ordenado)
    Me = len(A_ordenado)//2
    A_izq = A_ordenado[:Me].copy()
    A_der = A_ordenado[Me:].copy()
    return A_izq,A_der
A_izq,A_der = dividir_eje_mediana(A,ind_eje)
print(A_izq)
print(A_der)
eje_izq,ind_eje_izq = ind_maximo(varianza(A_izq))
eje_der,ind_eje_der = ind_maximo(varianza(A_der))
A_izq_izq,A_izq_der = dividir_eje_mediana(A_izq,ind_eje_izq)
A_der_izq,A_der_der = dividir_eje_mediana(A_der,ind_eje_der)
print("\n",A_izq_izq)
print("\n",A_izq_der)
print("\n",A_der_izq)
print("\n",A_der_der)
# python no tiene implementado una funcion que retorne el nombre de una variable variable.name() , una buena idea de implementacion aunque redundatne y quizas inutil, como sea, me ayudara bastante.
# hasta que la bola tenga un solo elemento
eje_izq_der, ind_eje_izq_der = ind_maximo(varianza(A_izq_der))
A_izq_der_izq,A_izq_der_der = dividir_eje_mediana(A_izq_der,ind_eje_izq_der)
eje_der_izq, ind_eje_der_izq = ind_maximo(varianza(A_der_izq))
A_der_izq_izq,A_der_izq_der = dividir_eje_mediana(A_der_izq,ind_eje_der_izq)
eje_der_der, ind_eje_der_der = ind_maximo(varianza(A_der_der))
A_der_der_izq,A_der_der_der = dividir_eje_mediana(A_der_der,ind_eje_der_der)
print("\n",A_izq_der_izq)
print("\n",A_izq_der_der)
print("\n",A_der_izq_izq)
print("\n",A_der_izq_der)
print("\n",A_der_der_izq)
print("\n",A_der_der_der)
# se queda unicamente con las hojas, como se observa, osea, esto es recursivo hasta obtener las hojas
# y esto es no facilmente, pero si de interesante implementacion



[[2 8]
 [5 3]
 [7 6]
 [1 4]
 [9 2]
 [4 7]
 [6 1]]
[4.85714286 4.42857143]
4.802210375420461
[np.float64(6.693877551020408), np.float64(5.959183673469389)]
X
[[1 4]
 [2 8]
 [4 7]]
[[5 3]
 [6 1]
 [7 6]
 [9 2]]

 [[1 4]]

 [[4 7]
 [2 8]]

 [[6 1]
 [9 2]]

 [[5 3]
 [7 6]]

 [[2 8]]

 [[4 7]]

 [[6 1]]

 [[9 2]]

 [[5 3]]

 [[7 6]]


In [ ]:
# el porque de claude
"""A_izq_izq = np.array([1,4])
```

Lo que ocurre en memoria es:
```
"A_izq_izq"  →  dirección 0x7f4a  →  array([1,4])
     ↑                ↑                    ↑
  nombre en        tabla de            objeto en
  el código        símbolos             memoria
```

El objeto `array([1,4])` vive en memoria y no tiene ninguna referencia hacia atrás a la tabla de símbolos. No sabe que existe `"A_izq_izq"`. Es una calle de un solo sentido:
```
nombre → objeto    ✓
objeto → nombre    ✗"""



In [ ]:
# El codigo siguiente fue generado por claude , claro ,respetando mi estilo y mis funciones 
# Podria aventurarme a programarlo yo mismo, pero siempre el tiempo es un cruel patron
