In [3]:
import numpy as np
import matplotlib.pyplot as plt
# 1 == A      0 == B

def cart(a):
    pA = np.sum(a[:,-1]==1)  
    pB = np.sum(a[:,-1]==0)
    print(f"pA ,pB : {pA},{pB}")
    IR = 1 - pA**2 - pB**2
    m,n = a.shape
    a_ord = np.sort(a,axis=0)
    for j in range(n-1):
        Cj = []
        for i in range(1,m):
            if a[i,j]!=a[i-1,j]:
                Cj.append((a[i,j]+a[i-1,j])/2)
        for e in Cj: #proporcion        
            R1 = a[:,j]<=e
            R2 = a[:,]>e
            #splits
    
    
if __name__=='__main__':
    a = np.array([[2,2,1],[3,1,1],[4,2,0],[5,3,0],[6,1,0]])
    print(a)
    arbol = cart(a)
















[[2 2 1]
 [3 1 1]
 [4 2 0]
 [5 3 0]
 [6 1 0]]
pA ,pB : 2,3


In [6]:
a = np.array([[2,2,1],[3,1,1],[4,2,0],[5,3,0],[6,1,0]])
print(a)
a_sort = np.sort(a,axis=0)
print(a_sort)
print(a)

[[2 2 1]
 [3 1 1]
 [4 2 0]
 [5 3 0]
 [6 1 0]]
[[2 1 0]
 [3 1 0]
 [4 2 0]
 [5 2 1]
 [6 3 1]]
[[2 2 1]
 [3 1 1]
 [4 2 0]
 [5 3 0]
 [6 1 0]]
