### Parte I (c/ejercicio vale 3 puntos)


#### Tests unitarios y ejercicios autocorregibles

A continuación se incluyen **tests unitarios** para las funciones que se deben implementar, así como **ejercicios autocorregibles** (con `TODO`) que los estudiantes pueden completar y verificar con *asserts*.



### EJERCICIO 1 — `mse(y_true, y_pred)` (autocorregible)

Implementa la función **MSE** (error cuadrático medio). Debe devolver un escalar flotante.


In [2]:

# TODO: Implementa el MSE sin usar sklearn
def mse(y_true, y_pred):
    #raise NotImplementedError("Función no implementada")
    return np.sum((y_true - y_pred)**2)/len(y_true)

In [6]:
import numpy as np
y_true = np.array([1,2,4]) 
y_pred = np.array([3,5,6])
print(f"mse = {mse(y_true,y_pred)}")

mse = 5.666666666666667


In [3]:
# TESTS EJERCICIO 1
import numpy as np
try:
    # Caso simple
    y_true = np.array([1., 2., 3.])
    y_pred = np.array([1., 2., 4.])
    val = mse(y_true, y_pred)
    assert np.isscalar(val), "mse debe devolver un escalar"
    assert abs(val - ((0**2 + 0**2 + 1**2)/3)) < 1e-12, f"Valor incorrecto: {val}"
    
    # Aleatorio reproducible
    rng = np.random.default_rng(0)
    y = rng.normal(size=100)
    yhat = y + rng.normal(scale=0.1, size=100)
    val2 = mse(y, yhat)
    assert val2 >= 0, "MSE no puede ser negativo"
    print(" EJ1 OK — mse() pasa los tests")
except NotImplementedError:
    print(" EJ1 pendiente: implementa mse() para pasar los tests")


 EJ1 OK — mse() pasa los tests



### EJERCICIO 2 — `add_bias(X)` (autocorregible)

Crea una función que añada una **columna de 1s** al principio de `X` para el término independiente.


In [4]:

# TODO: Implementa add_bias
import numpy as np
def add_bias(X):
    """Devuelve una nueva matriz con una columna de 1s al principio."""
    #raise NotImplementedError("Implementa add_bias")
    n, k  = X.shape 
    Xf = np.ones((n,k + 1))
    Xf[:,1:k+1] = X[:,0:k]
    print(Xf)
    return Xf
#probando en la misma celda con un array X de ejemplo
if __name__=='__main__':
    X = np.array([[3,2,4],[4,3,1],[5,6,1]])
    add_bias(X)

[[1. 3. 2. 4.]
 [1. 4. 3. 1.]
 [1. 5. 6. 1.]]


In [5]:
# TESTS EJERCICIO 2
import numpy as np
try:
    X = np.arange(6).reshape(3,2).astype(float)
    Xb = add_bias(X)
    assert Xb.shape == (3,3), f"Forma esperada (3,3), obtenida {Xb.shape}"
    assert np.allclose(Xb[:,0], 1.0), "La primera columna debe ser todo 1s"
    assert np.allclose(Xb[:,1:], X), "El resto de columnas deben coincidir con X"
    print(" EJ2 OK — add_bias() pasa los tests")
except NotImplementedError:
    print(" EJ2 pendiente: implementa add_bias() para pasar los tests")


[[1. 0. 1.]
 [1. 2. 3.]
 [1. 4. 5.]]
 EJ2 OK — add_bias() pasa los tests



### EJERCICIO 3 — `normal_equation(X,y)` (autocorregible)

Crea una función que calcule la ecuación normal


In [6]:
#TODO: Implementa la ecuación normal
import numpy as np
inv = np.linalg.inv
def ecuacion_normal(X, y):
   #raise NotImplementedError("Implementa normal_equation")
    theta = inv(X.T @ X )@(X.T @ y)
    print(theta)
    return theta

if __name__=='__main__':
    X = add_bias(np.array([[3,2,4],[4,3,1],[5,6,1]]))
    y = np.array([1,2,3])
    ecuacion_normal(X,y)
    

[[1. 3. 2. 4.]
 [1. 4. 3. 1.]
 [1. 5. 6. 1.]]
[32.  0. -2.  0.]


In [8]:
# TESTS EJ4
import numpy as np
inv = np.linalg.inv

try:
    X = add_bias(np.array([[1, 1], [3, 4], [5, 6]])) # se agrega la columna de 1's 
    y = np.array([[7], [8], [9]])
    theta = ecuacion_normal(X, y)
    assert theta.shape == (3, 1), f"Forma esperada (3,1), obtenida {theta.shape}"
    #y_pred = np.dot(np.c_[np.ones((X.shape[0], 1)), X], theta) , ya no es necesario pues add_bias ya hizo ello
    y_pred = X @ theta
    mse_val = np.mean((y - y_pred) ** 2)
    assert mse_val < 1e-10, f"MSE esperado cercano a 0, obtenido {mse_val}"
    print("EJ3 OK — normal_equation() pasa los tests")
except NotImplementedError:
    print("EJ3 pendiente: implementa normal_equation() para pasar los tests")
    

[[1. 1. 1.]
 [1. 3. 4.]
 [1. 5. 6.]]
[[6.5]
 [0.5]
 [0. ]]
EJ3 OK — normal_equation() pasa los tests
